In [39]:
import pandas as pd 
import numpy as np 
import scipy
from scipy.stats import chi2_contingency

In [2]:
data_non_null = pd.read_csv('../dataset/non_null_data.csv')
data_non_null

,Unnamed: 0,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,0,1.0,2015-02-06 22:24:17,2015-02-06 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0,american
1,1,2.0,2015-02-10 21:49:25,2015-02-10 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0,indian
2,8,2.0,2015-02-16 00:11:35,2015-02-16 00:38:01,5477,indian,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0,1586.0,indian
3,14,1.0,2015-02-12 03:36:46,2015-02-12 04:14:39,2841,italian,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0,2273.0,italian
4,15,1.0,2015-01-27 02:12:36,2015-01-27 03:02:24,2841,italian,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0,2988.0,italian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176467,197423,1.0,2015-02-17 00:19:41,2015-02-17 01:24:48,2956,fast,4.0,3,1389,3,345,649,17.0,17.0,23.0,251,331.0,3907.0,fast
176468,197424,1.0,2015-02-13 00:01:59,2015-02-13 00:58:22,2956,fast,4.0,6,3010,4,405,825,12.0,11.0,14.0,251,915.0,3383.0,fast
176469,197425,1.0,2015-01-24 04:46:08,2015-01-24 05:36:16,2956,fast,4.0,5,1836,3,300,399,39.0,41.0,40.0,251,795.0,3008.0,fast
176470,197426,1.0,2015-02-01 18:18:15,2015-02-01 19:23:22,3630,sandwich,1.0,1,1175,1,535,535,7.0,7.0,12.0,446,384.0,3907.0,sandwich
176471,197427,1.0,2015-02-08 19:24:33,2015-02-08 20:01:41,3630,sandwich,1.0,4,2605,4,425,750,20.0,20.0,23.0,446,134.0,2228.0,sandwich

In [3]:
df_non_null = data_non_null.copy()
df_non_null.shape

(176472, 19)

In [4]:
df_non_null.head()

,Unnamed: 0,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,0,1.0,2015-02-06 22:24:17,2015-02-06 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0,american
1,1,2.0,2015-02-10 21:49:25,2015-02-10 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0,indian
2,8,2.0,2015-02-16 00:11:35,2015-02-16 00:38:01,5477,indian,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0,1586.0,indian
3,14,1.0,2015-02-12 03:36:46,2015-02-12 04:14:39,2841,italian,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0,2273.0,italian
4,15,1.0,2015-01-27 02:12:36,2015-01-27 03:02:24,2841,italian,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0,2988.0,italian

In [5]:
df_non_null.drop('Unnamed: 0', axis=True,inplace=True)

In [6]:
df_non_null.head()

,market_id,created_at,actual_delivery_time,store_id,store_primary_category,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,1.0,2015-02-06 22:24:17,2015-02-06 23:27:16,1845,american,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0,american
1,2.0,2015-02-10 21:49:25,2015-02-10 22:56:29,5477,mexican,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0,indian
2,2.0,2015-02-16 00:11:35,2015-02-16 00:38:01,5477,indian,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0,1586.0,indian
3,1.0,2015-02-12 03:36:46,2015-02-12 04:14:39,2841,italian,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0,2273.0,italian
4,1.0,2015-01-27 02:12:36,2015-01-27 03:02:24,2841,italian,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0,2988.0,italian

In [7]:
df_non_null.dtypes

market_id                                       float64
created_at                                       object
actual_delivery_time                             object
store_id                                          int64
store_primary_category                           object
order_protocol                                  float64
total_items                                       int64
subtotal                                          int64
num_distinct_items                                int64
min_item_price                                    int64
max_item_price                                    int64
total_onshift_dashers                           float64
total_busy_dashers                              float64
total_outstanding_orders                        float64
estimated_order_place_duration                    int64
estimated_store_to_consumer_driving_duration    float64
delivery_time                                   float64
non_null_primary_category                        object
dtype: object

In [8]:
df_non_null.isna().sum()

market_id                                       0
created_at                                      0
actual_delivery_time                            0
store_id                                        0
store_primary_category                          0
order_protocol                                  0
total_items                                     0
subtotal                                        0
num_distinct_items                              0
min_item_price                                  0
max_item_price                                  0
total_onshift_dashers                           0
total_busy_dashers                              0
total_outstanding_orders                        0
estimated_order_place_duration                  0
estimated_store_to_consumer_driving_duration    0
delivery_time                                   0
non_null_primary_category                       0
dtype: int64

In [9]:
df_non_null["created_at"] = pd.to_datetime(df_non_null["created_at"])
df_non_null["actual_delivery_time"] = pd.to_datetime(df_non_null["actual_delivery_time"])

In [10]:
df_non_null.dtypes

market_id                                              float64
created_at                                      datetime64[ns]
actual_delivery_time                            datetime64[ns]
store_id                                                 int64
store_primary_category                                  object
order_protocol                                         float64
total_items                                              int64
subtotal                                                 int64
num_distinct_items                                       int64
min_item_price                                           int64
max_item_price                                           int64
total_onshift_dashers                                  float64
total_busy_dashers                                     float64
total_outstanding_orders                               float64
estimated_order_place_duration                           int64
estimated_store_to_consumer_driving_duration           float64
delivery_time                                          float64
non_null_primary_category                               object
dtype: object

In [17]:
df_non_null.drop(["created_at","actual_delivery_time","store_primary_category"],axis=1,inplace=True)

In [18]:
df_non_null.head()

,market_id,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,1.0,1845,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0,american
1,2.0,5477,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0,indian
2,2.0,5477,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0,1586.0,indian
3,1.0,2841,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0,2273.0,italian
4,1.0,2841,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0,2988.0,italian

In [33]:
df_non_null[df_non_null["non_null_primary_category"] == "NaN"]["non_null_primary_category"]

Series([], Name: non_null_primary_category, dtype: object)

In [36]:
df_non_null.corr(numeric_only=True)

,market_id,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time
market_id,1.000000,0.044832,-0.012462,0.003478,-0.000771,0.015423,-0.010916,-0.007314,0.074100,0.065210,0.068097,-0.052180,0.018944,-0.037916
store_id,0.044832,1.000000,0.013196,-0.009277,-0.012610,-0.013280,-0.006718,-0.016877,-0.023695,-0.024297,-0.021227,0.022421,-0.001225,-0.005791
order_protocol,-0.012462,0.013196,1.000000,0.007147,-0.051848,-0.024056,-0.043568,-0.090316,0.146610,0.151304,0.136146,-0.680059,-0.009711,-0.046923
total_items,0.003478,-0.009277,0.007147,1.000000,0.555125,0.758390,-0.389667,-0.053734,0.032005,0.029024,0.034748,-0.025762,0.006255,0.077411
subtotal,-0.000771,-0.012610,-0.051848,0.555125,1.000000,0.680734,0.038625,0.509783,0.131213,0.126134,0.130475,0.033556,0.037756,0.143616
num_distinct_items,0.015423,-0.013280,-0.024056,0.758390,0.680734,1.000000,-0.446638,0.047243,0.065887,0.060616,0.067846,0.000723,0.024254,0.106006
min_item_price,-0.010916,-0.006718,-0.043568,-0.389667,0.038625,-0.446638,1.000000,0.541173,0.042524,0.044189,0.041383,0.054139,0.004784,0.009018
max_item_price,-0.007314,-0.016877,-0.090316,-0.053734,0.509783,0.047243,0.541173,1.000000,0.133850,0.131877,0.131414,0.085242,0.029268,0.089321
total_onshift_dashers,0.074100,-0.023695,0.146610,0.032005,0.131213,0.065887,0.042524,0.133850,1.000000,0.943706,0.936115,-0.188086,0.045213,0.047270
total_busy_dashers,0.065210,-0.024297,0.151304,0.029024,0.126134,0.060616,0.044189,0.131877,0.943706,1.000000,0.932826,-0.194278,0.043943,0.060825
total_outstanding_orders,0.068097,-0.021227,0.136146,0.034748,0.130475,0.067846,0.041383,0.131414,0.936115,0.932826,1.000000,-0.174562,0.039208,0.122045
estimated_order_place_duration,-0.052180,0.022421,-0.680059,-0.025762,0.033556,0.000723,0.054139,0.085242,-0.188086,-0.194278,-0.174562,1.000000,-0.022334,0.068708
estimated_store_to_consumer_driving_duration,0.018944,-0.001225,-0.009711,0.006255,0.037756,0.024254,0.004784,0.029268,0.045213,0.043943,0.039208,-0.022334,1.000000,0.158498
delivery_time,-0.037916,-0.005791,-0.046923,0.077411,0.143616,0.106006,0.009018,0.089321,0.047270,0.060825,0.122045,0.068708,0.158498,1.000000

In [42]:
stat, p ,dof,expected = chi2_contingency(pd.crosstab(df_non_null["delivery_time"], df_non_null["non_null_primary_category"]))
p

0.9999999971649937

In [54]:
df_non_null.shape

(176472, 15)

In [56]:
cor = df_non_null.corr(numeric_only=True).abs().unstack()
cor

market_id      market_id                                       1.000000
               store_id                                        0.044832
               order_protocol                                  0.012462
               total_items                                     0.003478
               subtotal                                        0.000771
                                                                 ...
delivery_time  total_busy_dashers                              0.060825
               total_outstanding_orders                        0.122045
               estimated_order_place_duration                  0.068708
               estimated_store_to_consumer_driving_duration    0.158498
               delivery_time                                   1.000000
Length: 196, dtype: float64

In [49]:
l = [1,2,3,4,2]
ll = []
ls = set()
for i in range(0,len(l)):
    for j in range(0,i+1):
        ll.append((l[i], l[j]))
        ls.add((l[i],l[j]))

print(f"List {ll}")
print(f"set {ls}")

List [(1, 1), (2, 1), (2, 2), (3, 1), (3, 2), (3, 3), (4, 1), (4, 2), (4, 3), (4, 4), (2, 1), (2, 2), (2, 3), (2, 4), (2, 2)]
set {(4, 4), (2, 4), (2, 1), (4, 3), (3, 1), (1, 1), (4, 2), (2, 3), (3, 3), (2, 2), (3, 2), (4, 1)}

In [62]:
num_df = df_non_null.select_dtypes(exclude="object")

In [63]:
def get_redundant(df):
    cols = set()
    for i in range(0, df.shape[1]):
        for j in range(0,i+1):
            cols.add((df.columns[i], df.columns[j]))
    return cols

In [64]:
get_redundant(num_df)

{('delivery_time', 'delivery_time'),
 ('delivery_time', 'estimated_order_place_duration'),
 ('delivery_time', 'estimated_store_to_consumer_driving_duration'),
 ('delivery_time', 'market_id'),
 ('delivery_time', 'max_item_price'),
 ('delivery_time', 'min_item_price'),
 ('delivery_time', 'num_distinct_items'),
 ('delivery_time', 'order_protocol'),
 ('delivery_time', 'store_id'),
 ('delivery_time', 'subtotal'),
 ('delivery_time', 'total_busy_dashers'),
 ('delivery_time', 'total_items'),
 ('delivery_time', 'total_onshift_dashers'),
 ('delivery_time', 'total_outstanding_orders'),
 ('estimated_order_place_duration', 'estimated_order_place_duration'),
 ('estimated_order_place_duration', 'market_id'),
 ('estimated_order_place_duration', 'max_item_price'),
 ('estimated_order_place_duration', 'min_item_price'),
 ('estimated_order_place_duration', 'num_distinct_items'),
 ('estimated_order_place_duration', 'order_protocol'),
 ('estimated_order_place_duration', 'store_id'),
 ('estimated_order_place_duration', 'subtotal'),
 ('estimated_order_place_duration', 'total_busy_dashers'),
 ('estimated_order_place_duration', 'total_items'),
 ('estimated_order_place_duration', 'total_onshift_dashers'),
 ('estimated_order_place_duration', 'total_outstanding_orders'),
 ('estimated_store_to_consumer_driving_duration',
  'estimated_order_place_duration'),
 ('estimated_store_to_consumer_driving_duration',
  'estimated_store_to_consumer_driving_duration'),
 ('estimated_store_to_consumer_driving_duration', 'market_id'),
 ('estimated_store_to_consumer_driving_duration', 'max_item_price'),
 ('estimated_store_to_consumer_driving_duration', 'min_item_price'),
 ('estimated_store_to_consumer_driving_duration', 'num_distinct_items'),
 ('estimated_store_to_consumer_driving_duration', 'order_protocol'),
 ('estimated_store_to_consumer_driving_duration', 'store_id'),
 ('estimated_store_to_consumer_driving_duration', 'subtotal'),
 ('estimated_store_to_consumer_driving_duration', 'total_busy_dashers'),
 ('estimated_store_to_consumer_driving_duration', 'total_items'),
 ('estimated_store_to_consumer_driving_duration', 'total_onshift_dashers'),
 ('estimated_store_to_consumer_driving_duration', 'total_outstanding_orders'),
 ('market_id', 'market_id'),
 ('max_item_price', 'market_id'),
 ('max_item_price', 'max_item_price'),
 ('max_item_price', 'min_item_price'),
 ('max_item_price', 'num_distinct_items'),
 ('max_item_price', 'order_protocol'),
 ('max_item_price', 'store_id'),
 ('max_item_price', 'subtotal'),
 ('max_item_price', 'total_items'),
 ('min_item_price', 'market_id'),
 ('min_item_price', 'min_item_price'),
 ('min_item_price', 'num_distinct_items'),
 ('min_item_price', 'order_protocol'),
 ('min_item_price', 'store_id'),
 ('min_item_price', 'subtotal'),
 ('min_item_price', 'total_items'),
 ('num_distinct_items', 'market_id'),
 ('num_distinct_items', 'num_distinct_items'),
 ('num_distinct_items', 'order_protocol'),
 ('num_distinct_items', 'store_id'),
 ('num_distinct_items', 'subtotal'),
 ('num_distinct_items', 'total_items'),
 ('order_protocol', 'market_id'),
 ('order_protocol', 'order_protocol'),
 ('order_protocol', 'store_id'),
 ('store_id', 'market_id'),
 ('store_id', 'store_id'),
 ('subtotal', 'market_id'),
 ('subtotal', 'order_protocol'),
 ('subtotal', 'store_id'),
 ('subtotal', 'subtotal'),
 ('subtotal', 'total_items'),
 ('total_busy_dashers', 'market_id'),
 ('total_busy_dashers', 'max_item_price'),
 ('total_busy_dashers', 'min_item_price'),
 ('total_busy_dashers', 'num_distinct_items'),
 ('total_busy_dashers', 'order_protocol'),
 ('total_busy_dashers', 'store_id'),
 ('total_busy_dashers', 'subtotal'),
 ('total_busy_dashers', 'total_busy_dashers'),
 ('total_busy_dashers', 'total_items'),
 ('total_busy_dashers', 'total_onshift_dashers'),
 ('total_items', 'market_id'),
 ('total_items', 'order_protocol'),
 ('total_items', 'store_id'),
 ('total_items', 'total_items'),
 ('total_onshift_dashers', 'market_id'),
 ('total_onshift_dashers', 'max_item_price'),
 ('total_onshift_dashers', 'min_item_price'),
 ('total_onshift_dashers', 'num_distinct_items'),
 ('total_onshift_dashers', 'order_protocol'),
 ('total_onshift_dashers', 'store_id'),
 ('total_onshift_dashers', 'subtotal'),
 ('total_onshift_dashers', 'total_items'),
 ('total_onshift_dashers', 'total_onshift_dashers'),
 ('total_outstanding_orders', 'market_id'),
 ('total_outstanding_orders', 'max_item_price'),
 ('total_outstanding_orders', 'min_item_price'),
 ('total_outstanding_orders', 'num_distinct_items'),
 ('total_outstanding_orders', 'order_protocol'),
 ('total_outstanding_orders', 'store_id'),
 ('total_outstanding_orders', 'subtotal'),
 ('total_outstanding_orders', 'total_busy_dashers'),
 ('total_outstanding_orders', 'total_items'),
 ('total_outstanding_orders', 'total_onshift_dashers'),
 ('total_outstanding_orders', 'total_outstanding_orders')}

In [59]:
df_non_null.columns

Index(['market_id', 'store_id', 'order_protocol', 'total_items', 'subtotal',
       'num_distinct_items', 'min_item_price', 'max_item_price',
       'total_onshift_dashers', 'total_busy_dashers',
       'total_outstanding_orders', 'estimated_order_place_duration',
       'estimated_store_to_consumer_driving_duration', 'delivery_time',
       'non_null_primary_category'],
      dtype='object')

In [65]:
num_df.columns

Index(['market_id', 'store_id', 'order_protocol', 'total_items', 'subtotal',
       'num_distinct_items', 'min_item_price', 'max_item_price',
       'total_onshift_dashers', 'total_busy_dashers',
       'total_outstanding_orders', 'estimated_order_place_duration',
       'estimated_store_to_consumer_driving_duration', 'delivery_time'],
      dtype='object')

In [67]:
def get_top_corelated_col(df,n):
    cor = df.corr(numeric_only=True).abs().unstack()
    labels_to_drop = get_redundant(df)
    a_cor = cor.drop(labels=labels_to_drop).sort_values(ascending=False)
    return a_cor[0:n]
get_top_corelated_col(num_df,20)

total_onshift_dashers                         total_busy_dashers                0.943706
                                              total_outstanding_orders          0.936115
total_busy_dashers                            total_outstanding_orders          0.932826
total_items                                   num_distinct_items                0.758390
subtotal                                      num_distinct_items                0.680734
order_protocol                                estimated_order_place_duration    0.680059
total_items                                   subtotal                          0.555125
min_item_price                                max_item_price                    0.541173
subtotal                                      max_item_price                    0.509783
num_distinct_items                            min_item_price                    0.446638
total_items                                   min_item_price                    0.389667
total_busy_dashers                            estimated_order_place_duration    0.194278
total_onshift_dashers                         estimated_order_place_duration    0.188086
total_outstanding_orders                      estimated_order_place_duration    0.174562
estimated_store_to_consumer_driving_duration  delivery_time                     0.158498
order_protocol                                total_busy_dashers                0.151304
                                              total_onshift_dashers             0.146610
subtotal                                      delivery_time                     0.143616
order_protocol                                total_outstanding_orders          0.136146
max_item_price                                total_onshift_dashers             0.133850
dtype: float64

In [70]:
# from the above observation we can see that we have redundant features in our dataframe 
# we will remove either of them for in order to reduce the sparsity in our dataframe

no_red_feature = df_non_null.drop(["total_outstanding_orders","num_distinct_items","min_item_price"],axis=1)

In [71]:
no_red_feature.head()

,market_id,store_id,order_protocol,total_items,subtotal,max_item_price,total_onshift_dashers,total_busy_dashers,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,1.0,1845,1.0,4,3441,1239,33.0,14.0,446,861.0,3779.0,american
1,2.0,5477,2.0,1,1900,1400,1.0,2.0,446,690.0,4024.0,indian
2,2.0,5477,3.0,4,4771,1604,8.0,6.0,446,289.0,1586.0,indian
3,1.0,2841,1.0,1,1525,1525,5.0,6.0,446,795.0,2273.0,italian
4,1.0,2841,1.0,2,3620,2195,5.0,5.0,446,205.0,2988.0,italian

In [73]:
no_red_feature_cor = no_red_feature.corr(numeric_only=True)
no_red_feature_cor["delivery_time"]

market_id                                      -0.037916
store_id                                       -0.005791
order_protocol                                 -0.046923
total_items                                     0.077411
subtotal                                        0.143616
max_item_price                                  0.089321
total_onshift_dashers                           0.047270
total_busy_dashers                              0.060825
estimated_order_place_duration                  0.068708
estimated_store_to_consumer_driving_duration    0.158498
delivery_time                                   1.000000
Name: delivery_time, dtype: float64

In [78]:
df_non_null

,market_id,store_id,order_protocol,total_items,subtotal,num_distinct_items,min_item_price,max_item_price,total_onshift_dashers,total_busy_dashers,total_outstanding_orders,estimated_order_place_duration,estimated_store_to_consumer_driving_duration,delivery_time,non_null_primary_category
0,1.0,1845,1.0,4,3441,4,557,1239,33.0,14.0,21.0,446,861.0,3779.0,american
1,2.0,5477,2.0,1,1900,1,1400,1400,1.0,2.0,2.0,446,690.0,4024.0,indian
2,2.0,5477,3.0,4,4771,3,820,1604,8.0,6.0,18.0,446,289.0,1586.0,indian
3,1.0,2841,1.0,1,1525,1,1525,1525,5.0,6.0,8.0,446,795.0,2273.0,italian
4,1.0,2841,1.0,2,3620,2,1425,2195,5.0,5.0,7.0,446,205.0,2988.0,italian
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176467,1.0,2956,4.0,3,1389,3,345,649,17.0,17.0,23.0,251,331.0,3907.0,fast
176468,1.0,2956,4.0,6,3010,4,405,825,12.0,11.0,14.0,251,915.0,3383.0,fast
176469,1.0,2956,4.0,5,1836,3,300,399,39.0,41.0,40.0,251,795.0,3008.0,fast
176470,1.0,3630,1.0,1,1175,1,535,535,7.0,7.0,12.0,446,384.0,3907.0,sandwich
176471,1.0,3630,1.0,4,2605,4,425,750,20.0,20.0,23.0,446,134.0,2228.0,sandwich